# Generated by Django 5.1.3 on 2025-12-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('enterprise', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('code_department', models.CharField(default='DEF', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
