# Generated by Django 6.0 on 2026-01-05 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.AddField(
            model_name='account',
            name='display_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='account',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='users.enterprise', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
