# Generated by Django 6.0 on 2025-12-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_enterprise_alter_client_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='login',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
