# Generated by Django 6.0.1 on 2026-01-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_account_name_account_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email_confirmed',
            field=models.BooleanField(default=False, verbose_name='Email Confirmado'),
        ),
    ]
