# Generated by Django 5.1.3 on 2025-12-26 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_client_login_client_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='code_department',
        ),
    ]
