# Generated by Django 6.0.3 on 2026-03-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_account_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Código de Verificação'),
        ),
    ]
