# Generated by Django 5.1.3 on 2025-12-12 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=400)),
                ('status', models.CharField(choices=[('SEM', 'Sem atendimento'), ('ABE', 'Aberto'), ('FEC', 'Fechado')], default='SEM', max_length=3)),
                ('priority', models.CharField(choices=[('DEF', 'desconhecido'), ('BAX', 'Baixa'), ('MED', 'Média'), ('ALT', 'Alta'), ('URG', 'Urgente')], default='DEF', max_length=3)),
                ('opening_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('closing_date', models.DateTimeField(blank=True, null=True)),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='attachment/')),
                ('comments', models.CharField(blank=True, max_length=400, null=True)),
                ('attributed_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Tecnico', to='users.technical')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Categoria', to='tickets.category')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Usuario', to='users.client')),
            ],
        ),
    ]
