# Generated by Django 5.1.3 on 2026-01-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('DEF', 'desconhecido'), ('BAX', 'Baixa'), ('MED', 'Média'), ('ALT', 'Alta'), ('URG', 'Urgente')], max_length=3, unique=True, verbose_name='Prioridade do Ticket')),
                ('response_time_hours', models.IntegerField(default=4, verbose_name='Tempo para 1ª Resposta (Horas)')),
                ('resolution_time_hours', models.IntegerField(default=24, verbose_name='Tempo para Resolução (Horas)')),
            ],
        ),
        migrations.AddField(
            model_name='tickets',
            name='sla_resolution_due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vencimento Resolução'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='sla_response_due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vencimento 1ª Resposta'),
        ),
    ]
