# Generated by Django 6.0 on 2026-01-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='comments',
        ),
        migrations.AlterField(
            model_name='tickets',
            name='sla_resolution_due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='SLA resolution'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='sla_response_due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='SLA response'),
        ),
    ]
